"""Add homework grading fields

Revision ID: 058b7bcd5582
Revises: 2f4b26ebd0c2
Create Date: 2026-10-05 13:19:31.526863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058b7bcd5582'
down_revision: Union[str, Sequence[str], None] = '2f4b26ebd0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'homework_submissions',
        sa.Column('grade', sa.Integer(), nullable=True)
    )

    op.add_column(
        'homework_submissions',
        sa.Column('feedback', sa.Text(), nullable=True)
    )

    # ### end Alembic commands ###


def downgrade() -> None:

    """Downgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('homework_submissions', 'feedback')
    op.drop_column('homework_submissions', 'grade')

    # ### end Alembic commands ###
