"""Add quiz time limit

Revision ID: 2f304048cb1a
Revises: bc179a5733c7
Create Date: 2026-09-18 13:42:12.034426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f304048cb1a'
down_revision: Union[str, Sequence[str], None] = 'bc179a5733c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('time_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'time_limit')
    # ### end Alembic commands ###
