"""add lesson status

Revision ID: cc894eae169c
Revises: 86230fe1c9a3
Create Date: 2026-09-01 11:56:40.007412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc894eae169c'
down_revision: Union[str, Sequence[str], None] = '86230fe1c9a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'lessons',
    sa.Column(
        'status',
        sa.String(),
        nullable=False,
        server_default='draft'
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'status')
    # ### end Alembic commands ###
