"""add quiz option position

Revision ID: fe918b5e7e59
Revises: b9df10502db8
Create Date: 2026-09-14 20:54:37.340782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe918b5e7e59'
down_revision: Union[str, Sequence[str], None] = 'b9df10502db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_options', sa.Column('position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_options', 'position')
    # ### end Alembic commands ###
